### ISSUE TITLE
npm install error log

### ISSUE THREAD

**Issue by todrobbins** [cblgh/datradio#2]
```
npm WARN datradio@0.0.1 No repository field.

up to date in 6.214s

> datradio@0.0.1 build /Users/todrobbins/dev/playground/datradio
> date && browserify -t browserify-nodent -t [ sheetify -u sheetify-cssnext ] -p [ css-extract -o bundle.css ] -p common-shakeify -p browser-pack-flat/plugin app.js -g uglifyify > bundle.js

Wed Apr 18 12:07:55 MDT 2018
Error: Cannot find module 'sheetify' from '/Users/todrobbins/dev/playground/datradio'
    at /Users/todrobbins/dev/playground/datradio/node_modules/resolve/lib/async.js:50:31
    at processDirs (/Users/todrobbins/dev/playground/datradio/node_modules/resolve/lib/async.js:184:39)
    at ondir (/Users/todrobbins/dev/playground/datradio/node_modules/resolve/lib/async.js:199:13)
    at load (/Users/todrobbins/dev/playground/datradio/node_modules/resolve/lib/async.js:82:43)
    at onex (/Users/todrobbins/dev/playground/datradio/node_modules/resolve/lib/async.js:107:17)
    at /Users/todrobbins/dev/playground/datradio/node_modules/resolve/lib/async.js:12:69
    at FSReqWrap.oncomplete (fs.js:170:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! datradio@0.0.1 build: `date && browserify -t browserify-nodent -t [ sheetify -u sheetify-cssnext ] -p [ css-extract -o bundle.css ] -p common-shakeify -p browser-pack-flat/plugin app.js -g uglifyify > bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the datradio@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/todrobbins/.npm/_logs/2018-04-18T18_07_55_868Z-debug.log
```

Here's the entirety of the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle datradio@0.0.1~prebuild: datradio@0.0.1
6 info lifecycle datradio@0.0.1~build: datradio@0.0.1
7 verbose lifecycle datradio@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle datradio@0.0.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/todrobbins/dev/playground/datradio/node_modules/.bin:/Users/todrobbins/.rvm/gems/ruby-2.1.5/bin:/Users/todrobbins/.rvm/gems/ruby-2.1.5@global/bin:/Users/todrobbins/.rvm/rubies/ruby-2.1.5/bin:/usr/local/sbin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Users/todrobbins/.rvm/bin
9 verbose lifecycle datradio@0.0.1~build: CWD: /Users/todrobbins/dev/playground/datradio
10 silly lifecycle datradio@0.0.1~build: Args: [ '-c',
10 silly lifecycle   'date && browserify -t browserify-nodent -t [ sheetify -u sheetify-cssnext ] -p [ css-extract -o bundle.css ] -p common-shakeify -p browser-pack-flat/plugin app.js -g uglifyify > bundle.js' ]
11 silly lifecycle datradio@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle datradio@0.0.1~build: Failed to exec build script
13 verbose stack Error: datradio@0.0.1 build: `date && browserify -t browserify-nodent -t [ sheetify -u sheetify-cssnext ] -p [ css-extract -o bundle.css ] -p common-shakeify -p browser-pack-flat/plugin app.js -g uglifyify > bundle.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid datradio@0.0.1
15 verbose cwd /Users/todrobbins/dev/playground/datradio
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/Cellar/node/9.11.1/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v9.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error datradio@0.0.1 build: `date && browserify -t browserify-nodent -t [ sheetify -u sheetify-cssnext ] -p [ css-extract -o bundle.css ] -p common-shakeify -p browser-pack-flat/plugin app.js -g uglifyify > bundle.js`
22 error Exit status 1
23 error Failed at the datradio@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Please tell me if I'm doing something wrong! Thanks!

**Comment by cblgh** [comment]
It was my fault entirely, I had forgotten to add `sheetify`to `package.json`. If you pull and try `npm install && npm run build` again it should work! 

Otherwise you can try following this [tutorial], which handles everything via Beaker Browser instead. Let me know which you choose and how it works out. 

Thanks for the issue btw! :3
